version: 2.1
parameters:
  pull_request:
    type: boolean
    default: false

  target_branch:
    type: string
    default: ''

workflows:

  # Pull Requests Tests 
  on-pull-request-tests:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - tests:
          name: 'on-pull-request-tests'

  # feature,hotfix,bugfix Tests 
  on-push-tests:
    unless : 
      or:
        - equal: [ true, << pipeline.parameters.pull_request >> ]
        - equal: [ develop, << pipeline.git.branch >> ]
        - equal: [ uat, << pipeline.git.branch >> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - tests:
          name: 'on-push-tests'
  # DEV 
  build-and-deployment-to-dev:
    when:
      and:
        - equal: [ false, << pipeline.parameters.pull_request >> ]
        - equal: [ develop, << pipeline.git.branch >> ]
    jobs:
      - build:
          name: 'build-dev'
      - deploy:
          name: 'deploy-dev'
          requires:
            - build-dev
  
  # UAT
  build-and-deployment-to-uat:
    when:
      and:
        - equal: [ false, << pipeline.parameters.pull_request >> ]
        - equal: [ uat, << pipeline.git.branch >> ]
    jobs:
      - build:
          name: 'build-uat'
      - deploy:
          name: 'deploy-uat'
          requires:
            - build-uat
  
  # PROD
  build-and-deployment-to-prod:
    when:
      and:
        - equal: [ false, << pipeline.parameters.pull_request >> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build:
          name: 'build-prod'
      - deploy:
          name: 'deploy-prod'
          requires:
            - build-prod

  # Jobs definitions      
jobs:
  tests:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo "${CIRCLE_BRANCH} << pipeline.parameters.target_branch >>"
      - run:
          name: "Memory Stats"
          command:  |
            echo 'export FILE=memory-usage-actual.txt' >> $BASH_ENV
            while true;do
              ps -u circleci eo pid,%cpu,%mem,args,uname --sort=-%mem >> $FILE
              echo "------$(date +%Y%m%d%H%M%S)----" >> $FILE
              sleep 1
            done
          background: true
      - store_artifacts:
          path: "$FILE"
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}
